server:
  port: 9080
dubbo:
  application:
    name: provider
  registry:
    address: 192.168.223.133:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
  monitor:
    protocol: registry
